import '../styles/global.css';
import '../styles/styles.linaria.global';
import type { ReactNode, JSX } from 'react';

export default function RootLayout({ children }: { children: ReactNode }): JSX.Element {
	return (
		<html lang="en">
			<head>
				<title>Next App Dir with Linaria</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>{children}</body>
		</html>
	);
}
